services:
  # CONFIG SERVER
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - innernetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  # PostgreSQL Database
  postgres-products:
    image: postgres:15-alpine
    container_name: postgres-products
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_products:/var/lib/postgresql/data
    networks:
      - innernetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
    restart: unless-stopped

  postgres-merchants:
    image: postgres:15-alpine
    container_name: postgres-merchants
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=merchants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_merchants:/var/lib/postgresql/data
    networks:
      - innernetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
    restart: unless-stopped

  # REDIS SERVER
  redisserver:
    container_name: redisserver
    image: redis
    ports:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - innernetwork

  #EUREKA DISCOVERY SERVER
  discoveryserver:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discoveryserver
    ports:
      - "8761:8761"
    networks:
      - innernetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 60s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
      redisserver:
        condition: service_healthy
    restart: unless-stopped

  #PRODUCTS
  products:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: products
    expose:
      - "8082"
    networks:
      - innernetwork
    depends_on:
      config-server:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
      postgres-products:
        condition: service_healthy
      redisserver:
        condition: service_healthy
    restart: unless-stopped

  #MERCHANTS
  merchants:
    build:
      context: ./merchant
      dockerfile: Dockerfile
    container_name: merchants
    expose:
      - "8081"
    networks:
      - innernetwork
    depends_on:
      postgres-merchants:
        condition: service_healthy
      products:
        condition: service_started
    restart: unless-stopped

  #GATEWAY
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - innernetwork
    depends_on:
      merchants:
        condition: service_started
    restart: unless-stopped

  #ZIPKIN
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - innernetwork
    depends_on:
      gateway:
        condition: service_started

volumes:
  postgres_merchants:
  postgres_products:

networks:
  innernetwork:
    driver: bridge
    name: innernetwork