server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      failFast: true
      server:
        native:
          search-locations: classpath:/configurations
